### ISSUE TITLE
Support for asynchronous message handlers

### ISSUE THREAD

**Issue by DigitalSolomon** [insidegui/MultipeerKit#20]
Is there a way we can return a `CLIResponse` asynchronously, or do the message handling methods passed to `transceiver.receive` have to be synchronous calls which return a `String`?

**Comment by insidegui** [comment]
Not sure I fully understand the question.

The callback `receive` expects doesn't return anything, it's a `Void` closure.

If you're talking about async/await, you can have your callback perform asynchronous code by wrapping it in a `Task`, [like shown here](https://www.swiftbysundell.com/articles/connecting-async-await-with-other-swift-code/).

**Comment by DigitalSolomon** [comment]
Thanks for the quick response :) To clarify what I mean, let's take the `start()` method in `CLIReceiver.swift` for example.

```
func start() {
        transceiver.receive(ListDrivesCommand.self, using: response(handleFoo))
        transceiver.receive(SanityTestCommand.self, using: response(handleBar))
        transceiver.resume()
    }
```
Right now the `handleFoo` method which I pass to `response` is a synchronous method which returns `.message("sample-message")`. I want to be able to make an asynchronous call upon receiving the command to populate the `String` response. Do you know how to achieve this? I'll check out the link you provided.

**Comment by DigitalSolomon** [comment]
Also, if our project doesn't use `async/await` yet, are there other asynchronous options? Thanks

**Comment by insidegui** [comment]
Hmmmm, I'm a bit lost because the code you're sharing is not in the context of this repo. I assume that's one of your projects that's using the library, right?

There should be some way to plug an async method in there, or you can write your own little wrapper. That's out of the scope of Github issues for the library though, so I'm closing this issue.

John's concurrency discover page has lots of guides that could help you get started: https://www.swiftbysundell.com/discover/concurrency/

If that doesn't help, you may also ask your question in [Stackoverflow](https://stackoverflow.com).

I don't know of any other similar wrappers for MultipeerConnectivity. I have async/await support planned, but I won't have time to implement that any time soon.

**Comment by DigitalSolomon** [comment]
This is from the Listr sample app mentioned in this article [here](https://rambo.codes/posts/2020-03-01-writing-command-line-interfaces-for-ios-apps) (repo [here](https://github.com/insidegui/Listr)) . I thought this was also your project as well, but maybe I'm mistaken.

**Comment by insidegui** [comment]
Ah, it is. Sorry, I didn't make the connection based on your initial comment 😅

**Comment by DigitalSolomon** [comment]
No worries. I modified the code so that the handlers don't return a `CLIResponse` immediately, but instead return `Void` and receive an additional callback parameter which calsl `self?.transceiver.broadcast(CLIResponse.message(result))` after asynchronous activity has occurred. It's all working, just was curious if you had anything more elegant. Good work on your project overall! MultipeerKit is a nice wrapper around MultipeerConnectivity!

**Comment by insidegui** [comment]
Glad to know you found a solution :)
